[#86] Add support for providing `--data-dir` to CLI
zingolabs/zecwalletlitelib pull request #20
Opened 2022-05-19 16:37 UTC by AloeareV

In browsing the various forks of `zecwallet-light-cli`, this looks like useful functionality to have!

2022-05-20 01:18 UTC, zancas commented on lib/src/lightclient/lightclient_config.rs
> +                data_dir: data_dir,
Interesting, so there was a field in the struct, it just wasn't used.  Nice tweak.

2022-05-20 15:48 UTC, zancas approved these changes

2022-06-06 17:14 UTC, zancas commented on lib/Cargo.toml
> +zcash_primitives = { git = "https://github.com/adityapk00/librustzcash", rev = "b70edf39e26e4c687b5087daf2ffd40f99fffd67", features = ["transparent-inputs"] }
This looks like it needs to be rebased,   We shouldn't revert to pointing at legacy `librustzcash`.

2022-06-06 17:15 UTC, zancas requested changes
Points at legacy `librustzcash`.

2022-06-06 20:41 UTC, AloeareV commented
Closing in favour of #64

2022-06-06 20:41 UTC, closed without merging